In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
b=np.array([[2.0,3.1,4.5],[3.6,7.5,8.9]])
print(b)

[[2.  3.1 4.5]
 [3.6 7.5 8.9]]


In [5]:
a.ndim

1

In [8]:
print(type(b))

<class 'list'>


In [11]:
b.ndim


2

In [12]:
b.shape

(2, 3)

In [13]:
a.shape

(3,)

In [14]:
b.dtype


dtype('float64')

In [15]:
a.itemsize


8

In [16]:
a.nbytes


24

In [4]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14,]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
#get an specific element [r,c]
a[1,5]


np.int64(13)

In [7]:
#get specific rows and cols
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
#get specifc cols
a[:,2]

array([ 3, 10])

In [10]:
#getting an range of element [start _index:end_index:stepsize]

a[0,1:6:2]


array([2, 4, 6])

In [15]:
#changing the element
a[1,5]=20
print(a)

a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [21]:
#3d array element acccessing
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [25]:
#replace
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [28]:
#zeros array
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [29]:
#ones array
np.ones((2,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [31]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [32]:
#random elements
np.random.rand(4,2)

array([[0.78009463, 0.85279472],
       [0.62232907, 0.39881324],
       [0.4373062 , 0.12439232],
       [0.50043226, 0.54564663]])

In [35]:
np.random.random_sample(a.shape)

array([[0.95450808, 0.99882197, 0.74785621, 0.62963807, 0.84127063,
        0.79217873, 0.00462396],
       [0.96803671, 0.65290297, 0.06496164, 0.49054428, 0.16888166,
        0.75120043, 0.78715168]])

In [37]:
#identity matrix
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [41]:
arr=np.array([[1,2,3],[4,5,6]])
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


In [13]:
# building a matrix
import numpy as np
output=np.ones((5,5),dtype=int)
print(output)

z=np.zeros((3,3),dtype=int)


z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [21]:
#copying of the matrix

a=([1,2,3])


b=a.copy()  
b[0]=100
print(a)
print(b)

[1, 2, 3]
[100, 2, 3]


In [22]:
# MATHEMATICS
a=np.array([1,2,3,4])

print(a)



[1 2 3 4]


In [23]:
a+2

array([3, 4, 5, 6])

In [24]:
a-2

array([-1,  0,  1,  2])

In [25]:
a*2

array([2, 4, 6, 8])

In [26]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [27]:
b=np.array([5,6,7,8])

a+b


array([ 6,  8, 10, 12])

In [28]:
a**2



array([ 1,  4,  9, 16])

In [29]:
# TRIGO
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [30]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### LINEAR ALGEBRA


In [40]:
#MATRIX MULTIPLICATION
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [45]:
#detrminant
a=np.identity(3)
print(a)
np.linalg.det(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

#### statistics



In [4]:

import numpy as np 
stats=np.array([[1,2,3,4],[5,6,7,8]])

print(stats)
np.min


[[1 2 3 4]
 [5 6 7 8]]


<function min at 0x00000244FF22A230>

In [5]:
np.min(stats)

np.int64(1)

In [6]:
np.max(stats)

np.int64(8)

In [7]:
np.min(stats,axis=0) #axis=0 means compare row column wise

array([1, 2, 3, 4])

In [9]:
np.max(stats,axis=1) #axis=1 means compare row wise 

array([4, 8])

### reorganizing array

In [16]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after =before.reshape((8,1))

print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


# STACKING VECTORS

In [25]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a,b)

np.vstack((a,b))

np.hstack((a,b))

np.column_stack((a,b))

[1 2 3 4] [5 6 7 8]


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# loading the data file

In [6]:
import numpy as np
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([  1,   2,   3,  45, 667, 776,  88,  76,  76,  90], dtype=int32)

# boolean masking and advance indexing


In [7]:
filedata<50

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [8]:
filedata[filedata<50]

array([ 1,  2,  3, 45], dtype=int32)

In [11]:

a=np.array([1,2,3,4,5,6,7,8,9])

a[[1,3,5]]

array([2, 4, 6])